### ISSUE TITLE
Impossible to write to .csv

### ISSUE THREAD

**Issue by hwkinderman** [michaelminn/mmqgis#19]
It is not possible to write geometry to a .csv file. Also it is impossible to overwrite existing .csv files, which makes the destination directory cluttered if something fails. Below you can find the error.

AttributeError: 'QgsVectorFileWriter' object has no attribute 'writerow' 
Traceback (most recent call last):
  File "C:/Users/HendrikKinderman/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mmqgis\mmqgis_dialogs.py", line 1594, in run
    attribute_file_name, field_delimiter, line_terminator, self.mmqgis_status_callback)
  File "C:/Users/HendrikKinderman/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mmqgis\mmqgis_library.py", line 3011, in mmqgis_geometry_export_to_csv
    node_file.writerow(row)
AttributeError: 'QgsVectorFileWriter' object has no attribute 'writerow'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.1-Zanzibar Zanzibar, dcd95cc648 

Python Path:
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python
C:/Users/HendrikKinderman/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/HendrikKinderman/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.8\bin\python37.zip
C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib
C:\Program Files\QGIS 3.8\bin
C:\PROGRA~1\QGIS3~1.8\apps\Python37
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\Pythonwin
C:/Users/HendrikKinderman/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\HendrikKinderman\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\b4udignl2
C:\Users\HendrikKinderman\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\HendrikKinderman\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\HendrikKinderman\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\HendrikKinderman\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
V:/Wind/GEMBA/XXX
C:\Users\HendrikKinderman\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

**Comment by hwkinderman** [comment]
Unfortunately it was a problem with a geometry which seemed to be invalid.
